# Generated by Django 4.0.2 on 2023-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'elf'), ('Dwarf', 'dwarf'), ('Human', 'human'), ('Ork', 'ork')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='bonus',
            field=models.CharField(max_length=255, verbose_name='This field describes what kind of bonus players can get from it.'),
        ),
    ]
