# Generated by Django 4.0.2 on 2023-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_player_bio_alter_race_name_alter_skill_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'elf'), ('Dwarf', 'dwarf'), ('Human', 'human'), ('Ork', 'ork')], default='BB', max_length=255, unique=True),
        ),
    ]
